name       : perl-module-build-tiny
version    : 0.039
release    : 4
source     :
    - http://search.cpan.org/CPAN/authors/id/L/LE/LEONT/Module-Build-Tiny-0.039.tar.gz : 7d580ff6ace0cbe555bf36b86dc8ea232581530cbeaaea09bccb57b55797f11c
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : A tiny replacement for Module::Build
description: |
    A tiny replacement for Module::Build
builddeps  :
    - perl-extutils-config
    - perl-extutils-helpers
    - perl-extutils-installpaths
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    $workdir/Build install --destdir=$installdir
check      : |
    $workdir/Build test
