name       : perl-module-build-tiny
version    : '0.046'
release    : 7
source     :
    - https://cpan.metacpan.org/authors/id/L/LE/LEONT/Module-Build-Tiny-0.046.tar.gz : be193027e2debb4c9926434aaf1aa46c9fc7bf4db83dcc347eb6e359ee878289
homepage   : https://metacpan.org/pod/Module::Build::Tiny
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : A tiny replacement for Module::Build
description: |
    Module::Build::Tiny - A tiny replacement for Module::Build
builddeps  :
    - perl-extutils-config
    - perl-extutils-helpers
    - perl-extutils-installpaths
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    $workdir/Build install --destdir=$installdir
check      : |
    $workdir/Build test
